# Generated by Django 6.0.7 on 2026-07-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_businessinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('tailoring', 'Tailoring'), ('beads', 'Bead Making'), ('bags', 'Bead Bags'), ('fascinators', 'Fascinators'), ('tailoring_materials', 'Tailoring Materials'), ('bridal', 'Bridal Outfits'), ('traditional', 'Traditional Wear'), ('ready_to_wear', 'Ready-to-Wear')], max_length=20),
        ),
    ]
