# Generated by Django 6.0.7 on 2026-07-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_statistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
