# Generated by Django 6.0.7 on 2026-07-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_statistic_is_active_alter_service_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessinfo',
            options={'verbose_name': 'Business Information', 'verbose_name_plural': 'Business Information'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='preferred_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('clothes', 'Clothes'), ('beads', 'Bead Accessories'), ('bead_bags', 'Bead Bags'), ('fascinators', 'Fascinators'), ('tailoring_materials', 'Tailoring Materials'), ('bridal', 'Bridal Outfits'), ('traditional', 'Traditional Wear'), ('ready_to_wear', 'Ready-to-Wear')], db_index=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['category', 'featured'], name='core_galler_categor_394a86_idx'),
        ),
    ]
