# Generated by Django 6.0.7 on 2026-07-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_businessinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(help_text='Bootstrap Icon name (e.g. scissors, gem, handbag)', max_length=50),
        ),
    ]
