# Generated by Django 6.0.7 on 2026-07-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_appointment_created_at_alter_service_icon'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='gallery',
            name='core_galler_categor_394a86_idx',
        ),
    ]
