# Generated by Django 6.0.7 on 2026-07-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_gallery_core_galler_categor_394a86_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='image_height',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image_width',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to='gallery/', width_field='image_width'),
        ),
    ]
